esphome:
  name: example-esp8266

external_components:
  - source: github://buzzer13/esphome-components@main
    components:
      - tm1650

time:
  - platform: homeassistant
    id: tm_hass

i2c:
  - id: i2c_main
    sda: 13
    scl: 12
    scan: true

display:
  - platform: tm1650
    id: disp_tm1650
    # i2c_id: i2c_main
    # intensity: 1
    # length: 4
    # mode: 0
    # power: true
    # segment_map: PABCDEFG
    # backward: True
    update_interval: 500ms
    lambda: |-
      static int dot = 0;

      if (++dot & 1) {
        it.strftime("%H.%M", id(tm_hass).now());
      } else {
        it.strftime("%H%M", id(tm_hass).now());
      }
